### ISSUE TITLE
Add linux Arm64 support

### ISSUE THREAD

**Issue by PixelTheDev** [panda3d/panda3d#1178] opened 2021-07-24 20:59 UTC
## Description

Hello, I request support for arm64 architecture in pipy, becuase I use a raspberry pi as a computer and I would want to use this library.

## Use Case

It will help for people with a low cost pc, like the new mac, that is already supported.

**Comment by Revers-BR** [comment] 2021-08-15 19:44
> ## Description
> Hello, I request support for arm64 architecture in pipy, becuase I use a raspberry pi as a computer and I would want to use this library.
> 
> ## Use Case
> It will help for people with a low cost pc, like the new mac, that is already supported.

I downloaded a compiled version of panda3d for armhf and it works perfectly.

**Comment by Moguri** [comment] 2021-09-30 03:12
Looks like [manylinux2014](https://packaging.python.org/specifications/platform-compatibility-tags/#platform-tags-for-common-linux-distributions) has tags for armv7 and aarch64, but a recent enough pip version (19.3) is needed to recognize the new platform tags.

When Panda3D gets to building manylinux2014 wheels, we should look into what it takes to build for these arm platforms.

**Comment by rdb** [comment] 2021-09-30 10:31
I have done quite a bit of work on getting the buildbot to build arm64 wheels, via docker buildx's multiarch support, but the main problem is that the build process keeps locking up when building manylinux2014 container for arm64.  (We need to build our own manylinux2014 container because the official ones don't ship with libpythonX.Y.a, which we need for deploy-stub).  It's been a real pain to debug this because of the long time spent waiting for things to rebuild after making a change.

See pypa/manylinux#91 — if they were to fix that, then this would become so much easier for us.

That said, perhaps we could in the meantime disable building deploy-stub for arm64, it'll just mean that deploying for arm64 is not yet possible.

**Comment by rdb** [comment] 2021-09-30 10:32
Duplicate of #1113

**Closed by rdb** 2021-09-30 10:32 UTC
Labels: enhancement

**Comment by rdb** [comment] 2022-01-20 12:21
1.10.11 manylinux2014-aarch64 wheels have been uploaded to PyPI for Python 3.6 through 3.10.
