### ISSUE TITLE
Visual artifacts visible in animations with Cull/Draw thread model

### ISSUE THREAD

**Issue by nosyliam** [panda3d/panda3d#256] opened 2018-02-25 03:06 UTC
With the Cull/Draw thread model, various animations in my application will produce very visible artifacts. An example:
![image](https://user-images.githubusercontent.com/9064955/36637649-89b298b0-1995-11e8-8701-146661b1cbbb.png)

To reproduce this issue, I would simply have an actor playing an animation.

**Comment by theclashingfritz** [comment] 2018-02-25 07:29
Ouch, That hurts

**Comment by CFSworks** [comment] 2018-02-25 08:03
I'm having some difficulty reproducing this issue. Per the directions provided I wrote [this script](https://gist.github.com/CFSworks/0b716d3809bda140b2c75fcf46628d35) which produces normal-looking output on the latest master:

![image](https://user-images.githubusercontent.com/700768/36639311-4541a450-19c7-11e8-92dc-2e4176cf8941.png)

Could you provide a screenshot of what that test case looks like for you? Which platform and renderer backend are you using?

**Comment by CFSworks** [comment] 2018-03-05 08:20
Panda currently does not use CyclerData to manage the state of a character, so there is currently no guarantee of consistency in output frames.

I'm closing this in favor of #272 (which is the issue for tracking adding such support).

**Closed by CFSworks** 2018-03-05 08:20 UTC
