### ISSUE TITLE
Panda3D Compilation

### ISSUE THREAD

**Issue by theclashingfritz** [panda3d/panda3d#200] opened 2017-11-26 06:58 UTC
On Windows 8 with Visual Studio 10 building Panda3D (latest) statically returns this as an error.

`panda3d/dtool/src/dtoolbase/dlmalloc_src.cxx:1678:18: error: unknown type '__forceinline'
static FORCEINLINE void* win32mmap(size_t size) {
                 ^
panda3d/dtool/src/dtoolbase/dl
malloc_src.cxx:1678:20: error: syntax error, unexpected KW_VOID
static FORCEINLINE void* win32mmap(size_t size) {
                   ^~~~
Error parsing file: 'p3dtoolbase_composite1.cxx'
Storing dependency cache.
Elapsed Time: 2 min 43 sec
The following command returned a non-zero value: prebuilt/windows/interrogate.exe -srcdir dtool/src/dtoolbase -Idtool/src/dtoolbase -DCPPPARSER -D__STDC__=1 -D__cplusplus=201103L -DWIN32_VC -DWIN32 -D_WIN32 -D_M_IX86 -D_MSC_VER=1600 -D"__declspec(param)=" -D__cdecl -D_near -D_far -D__near -D__far -D__stdcall -oc built/tmp/libp3dtoolbase_igate.cxx -od built/pandac/input/libp3dtoolbase.in -fnames -string -refcount -assert -python-native -Sbuilt/include/parser-inc -Idtool/src/dtoolbase -Sbuilt/tmp -Sbuilt/include -Sthirdparty/win-python/include -Sthirdparty/win-libs-vc10/eigen\include -Sthirdparty/win-libs-vc10/python/include -Sthirdparty/win-libs-vc10/extras/include -DLINK_ALL_STATIC= -DEIGEN_NO_STATIC_ASSERT= -module panda3d.core -library libp3dtoolbase p3dtoolbase_composite1.cxx p3dtoolbase_composite2.cxx typeHandle.h typeHandle_ext.h typeRegistry.h typedObject.h neverFreeMemory.h
`

**Comment by rdb** [comment] 2017-11-27 17:51
I couldn't reproduce it, but there is no reason interrogate should be including that file, so I checked in a change that avoids that.

**Closed** 2017-11-27 17:50 UTC

**Comment by theclashingfritz** [comment] 2017-11-27 19:00
Thanks,
