### ISSUE TITLE
Python 3 Datagram invalid start byte

### ISSUE THREAD

**Issue by thetestgame** [panda3d/panda3d#297] opened 2018-04-05 22:48 UTC
When using datagrams with valid data in them on Python 3 any call to get_message results in the following error

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 10: invalid start byte
```

**Comment by CFSworks** [comment] 2018-04-05 22:53
@thetestgame Looks like this is caused by `Datagram::get_message()` being declared as a `string` return value even though it returns binary data. Does using `get_array()` instead resolve the exception?

@rdb Any reason why member methods meant to return binary data are declared as returning `string`? Interrogate treats `string` as UTF-8 encoded data - is that the convention (and should anything that returns binary data be replaced with a `vector_uchar` return type instead)?

**Comment by thetestgame** [comment] 2018-04-05 22:55
@CFSworks I've been messing with that. In this current case I'm actually using Astron and having to manually hand edit the internal repository for this. I also have some use cases I need the string get_message which i'm still working on resolving.

**Comment by thetestgame** [comment] 2018-04-05 22:59
@CFSworks Perhaps you have some input on this. Current I had a get_message being sent to the UberDog to be stored in the database. Its not erroring the DB interface.

**Comment by CFSworks** [comment] 2018-04-05 23:02
As long as the bytes in `get_message()` are all less than 128 then it'll be a valid ASCII string, and by extension, accepted by the UTF8 codec.

The best stopgap for now would probably be to change the return value of `get_message()` to `vector_uchar` on your local copy of Panda3D - because at any rate, it's unintended that `get_message()` should return a string (instead of a bytes) on Python 3.

**Comment by rdb** [comment] 2018-04-05 23:03
I have been working on this.  I'll submit a PR tomorrow.

**Comment by rdb** [comment] 2018-04-06 09:47
So to reiterate, the issue here is that in the C++ codebase we don't historically distinguish between UTF-8 strings and byte strings, whereas Python 3 does.  In recent times I have begun to introduce the notion that `string` always is UTF-8 encoded, whereas we capture byte strings using `vector_uchar`, which has a bit of historical precedent in Panda.  (In the C++17 future, we might also consider supporting `basic_string<std::byte>` or `vector<std::byte>`.)

The code here just hasn't been updated to deal with it.  But, there's still a large amount of C++ code that uses `get_message()` expecting it to return a string, so I will probably add a separate way to get hold of the data as a bytes object.

I also have some local changes that changes DCPacker to use vector_uchar everywhere a byte string is used.

**Comment by rdb** [comment] 2018-04-06 16:45
It's now possible to use `bytes(dg)` to get the byte representation for a datagram.

**Comment by CFSworks** [comment] 2018-04-06 20:00
Reopening since the issue is about `get_message()` being a completely broken function on Python 3 (meaning Python code meant to work on both versions cannot rely on it) and the `bytes(dg)` alternative is only available on Python 3 (meaning if said Python code switched to it, it'd just be trading "broken on 3" for "broken on 2" and therefore isn't a viable alternative for cross-Python support).

I have no problem with the `bytes(dg)` mechanism being around as a convenience, but I think the way to fix this is to change the return type of `get_message()`, otherwise we're just leaving a broken function in our Python 3 API.

Assigning this to myself - I'll get to it this weekend.

**Comment by abtechmg** [comment] 2018-08-17 19:33
Curious on this, do we have to edit a C++ file to get this working now? Or is there a python method to get past this. Been trying to get past this issue myself.

**Comment by rdb** [comment] 2018-08-17 19:37
No need; you can use `bytes(dg)` as an alternative for `dg.getMessage()` that works in Python 3.

**Comment by CFSworks** [comment] 2018-08-17 20:06
Be advised that `bytes(dg)` will _only_ work in Python 3: it will (silently) break compatibility with Python 2.

Currently, you will have to decide whether you want your Datagram-processing logic to be compatible with 3 or 2, or write some function that switches between `bytes(dg)`/`dg.getMessage()` depending on the major version of the Python interpreter.

**Comment by rdb** [comment] 2018-08-17 20:10
@cfsworks will you take this on soon, or should I take this over from you?

**Comment by abtechmg** [comment] 2018-08-17 20:29
One of the main reasons i ask, is cause even if i use bytes(dg), it gives another error.

`TypeError: bad argument type for built-in operation `

This is using the latest development build.

**Comment by rdb** [comment] 2018-08-17 20:33
I cannot reproduce that.  What Python version?  Can you give me a few lines of code that would reproduce this error?

**Comment by abtechmg** [comment] 2018-08-17 20:39
This is a snippet from my edited AstronInternalRepository:

```
    def addPostRemove(self, dg):
        """
        Register a datagram with the Message Director that gets sent out if the
        connection is ever lost.

        This is useful for registering cleanup messages: If the Panda3D process
        ever crashes unexpectedly, the Message Director will detect the socket
        close and automatically process any post-remove datagrams.
        """
        if sys.version_info > (3, 0):
            self.notify.info('Using Python 3.0 addPostRemove.')
            dg2 = PyDatagram()
            dg2.addServerControlHeader(CONTROL_ADD_POST_REMOVE)
            dg2.addUint64(self.ourChannel)
            print(bytes(dg)) # this actually prints
            dg2.addString(bytes(dg)) # issue occurs here, all i did was replace dg.getMessage()
        else:
            self.notify.info('Using Python 2.0 addPostRemove.')
            dg2 = PyDatagram()
            dg2.addServerControlHeader(CONTROL_ADD_POST_REMOVE)
            dg2.addUint64(self.ourChannel)
            dg2.addString(dg.getMessage())
        self.send(dg2)
```
I would have assumed this would've worked here too, but i guess not. I can however print the datagram!

**Comment by rdb** [comment] 2018-08-17 20:45
The problem is not in `bytes(dg)` there, but in `addString`.  It expects a string, not bytes.  If you wish to add binary data to a datagram, you should be using `appendData`.

**Comment by rdb** [comment] 2018-08-17 20:52
@abtechmg I forgot to mention that addString also adds a preceding 16-bit length integer, so your new code becomes:
```python
dg2.addUint16(dg2.getLength())
dg2.appendData(bytes(dg2))
```
Perhaps we should also be adding a `Datagram.addBlob` to take over this function for binary data.

**Comment by abtechmg** [comment] 2018-08-17 22:02
Alright, thank you. I got it loading without `dg2.addUint16(dg.getLength())` but if any issues arise i'll try that. Have a nice day you two!

**Comment by rdb** [comment] 2018-08-17 22:45
You really should add that.  It will most certainly do the wrong thing if you omit writing the length, and you really don't want to have obscure-bugs-waiting-to-happen lurking about in your code.

**Closed** 2018-08-19 15:12 UTC

**Comment by rdb** [comment] 2018-08-19 17:38
I have pushed a change that makes `get_message` return a bytes object in Python 3, via a custom extension function (changing the C++ return type would have meant changing a lot of C++ code).  `get_message()` now does the right thing in both Python 2 and 3.  This approach is more efficient as well as it avoids the unnecessary copy.

I have also added `add_blob` and `add_blob32` mirroring `add_string` and `add_string32` but for binary data in b1d21110372250b1c91a3829ae0c3f809a7d99d2.  This works fine in both Python 2 and 3.

To take @abtechmg's function as example, the function body can now be reduced to the following Python-version-agnostic code:
```
        dg2 = PyDatagram()
        dg2.addServerControlHeader(CONTROL_ADD_POST_REMOVE)
        dg2.addUint64(self.ourChannel)
        dg2.addBlob(dg.getMessage())
        self.send(dg2)
```
