### ISSUE TITLE
Video card select

### ISSUE THREAD

**Issue by VladimirCourse** [panda3d/panda3d#868] opened 2020-02-16 15:12 UTC
I have a laptop with Intel integrated video card and Nvidia discrete card. By default it runs with integrated card. Is there is a way or config option how to switch it to Nvidia card?

**Comment by serkkz** [comment] 2020-02-16 15:17
As far as I know this is configured in the Nvidia driver, you can set the preferred graphical interface for the program.

**Comment by VladimirCourse** [comment] 2020-02-16 15:27
> As far as I know this is configured in the Nvidia driver, you can set the preferred graphical interface for the program.

Yes, but I need to do it for python.exe which means I will run every program with Nvidida card. There is not way to setup it only for one script or .bat file just for Panda3d program

**Comment by serkkz** [comment] 2020-02-16 16:26
Hmm, I don't know exactly, you can do it programmatically like this. However, I don't know how this is implemented in Panda.

http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf

You may need to make changes to the source code.

**Comment by Moguri** [comment] 2020-02-16 19:38
Unfortunately, there is not a good way to control this after the program has launched. This is discussed as part of #680, and I am going to close this as a duplicate of #680. Please move further discussion to that issue.

**Closed by Moguri** 2020-02-16 19:38 UTC
Labels: duplicate
