### ISSUE TITLE
build fail on Mac OS Mojave 10.14

### ISSUE THREAD

**Issue by zodiacsm** [panda3d/panda3d#679] opened 2019-06-28 02:47 UTC
I'm compiling panda3D on my macos 10.14,but get these errors, I have tried to fix this by add 
following code to the build file, but still get these errors.

if GetTarget() == "darwin" and not PkgSkip("OPENAL"):
     LibName("OPENAL", "-framework AudioToolbox")

shimings-MBP:panda3d shiming$ python makepanda/makepanda.py --everything --installer
Version: 1.11.0
Platform: macosx-10.14-x86_64
Using Python 2.7
=========================================================================
WARNING: Python 2.7 will reach EOL after December 31, 2019, and will not
WARNING: be supported after that date.  Please ensure you are prepared
WARNING: by planning your upgrade to Python 3 now.
=========================================================================
Target OS: darwin
Target arch: x86_64
WARNING: Could not locate thirdparty package fftw, excluding from build
WARNING: Could not locate thirdparty package gles, excluding from build
WARNING: Could not locate thirdparty package gles2, excluding from build
WARNING: Could not locate thirdparty package egl, excluding from build
WARNING: Could not locate pkg-config package gtk+-2.0, excluding from build
Generating dependencies...
WARNING: file depends on Python but is not in an ABI-specific directory: built/bin/p3dcparse
WARNING: file depends on Python but is not in an ABI-specific directory: built/bin/deploy-stub
WARNING: file depends on Python but is not in an ABI-specific directory: built/bin/deploy-stubw
[ 42%] Linking dynamic library built/lib/libp3openal_audio.dylib
Undefined symbols for architecture x86_64:
  "_AudioObjectGetPropertyData", referenced from:
      _ALCcoreAudioCapture_ALCbackend_open in libopenal.a(coreaudio.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Storing dependency cache.
Elapsed Time: 9 sec
The following command returned a non-zero value: clang++ -dynamiclib -install_name @loader_path/../lib/libp3openal_audio.dylib -compatibility_version 1.11 -current_version 1.11.0 -o built/lib/libp3openal_audio.dylib -Lbuilt/lib -Lbuilt/tmp built/tmp/openal_audio_openal_audio_composite1.o built/lib/libpanda.dylib built/lib/libpandaexpress.dylib built/lib/libp3dtool.dylib built/lib/libp3dtoolconfig.dylib -headerpad_max_install_names -stdlib=libc++ -arch x86_64 thirdparty/darwin-libs-a/openal/lib/libopenal.a -framework AudioToolbox -framework AppKit -ldl
Build terminated.

**Comment by rdb** [comment] 2019-07-10 08:01
Duplicate of #678, except in this case `-framework CoreAudio` is missing.

**Closed** 2019-07-10 12:44 UTC
Labels: duplicate
