### ISSUE TITLE
Vulkan failing to start up at the validation layer

### ISSUE THREAD

**Issue by nosyliam** [panda3d/panda3d#211] opened 2017-12-14 08:04 UTC
I've compiled static libraries for embedding a Panda3D application with Vulkan support (from the vulkan branch). Whenever I try to start up my program, I'm greeted with this:
```
Known pipe types:
  TinyWinGraphicsPipe
  TinyOffscreenGraphicsPipe
  wglGraphicsPipe
  VulkanGraphicsPipe
(all display modules loaded.)
:display:windisplay: OS version: 6.2.2.9200
:display:windisplay:
:display:windisplay: max Mhz 2601000000, current Mhz 800000000
:Base: Default graphics pipe is VulkanGraphicsPipe (Vulkan).
:display:vulkandisplay(warning): vkCreateSampler: value of pCreateInfo->anisotropyEnable (167) is neither VK_TRUE nor VK_FALSE
:display:vulkandisplay(warning): vkCreateSampler: value of pCreateInfo->compareEnable (10944877) is neither VK_TRUE nor VK_FALSE
:display:vulkandisplay(error): vkCreateRenderPass: parameter pCreateInfo->flags must be 0. The spec valid usage text states 'flags must be 0' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkRenderPassCreateInfo-flags-zerobitmask)
:display:vulkandisplay(error): vkCreateImageView: value of pCreateInfo->subresourceRange.aspectMask contains flag bits that are not recognized members of VkImageAspectFlagBits
:display:vulkandisplay(error): vkCreateImageView(): Combination depth/stencil image formats can have only the VK_IMAGE_ASPECT_DEPTH_BIT and VK_IMAGE_ASPECT_STENCIL_BIT set. The spec valid usage text states 'aspectMask must be a valid combination of VkImageAspectFlagBits values' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageSubresource-aspectMask-parameter)
```

I am using MSVC 2010 and Windows SDK 7.1. I've also tested with Vulkan SDK versions 1.0.30.0, 1.0.49.0, and 1.0.65.1, linking to vulkan-1.lib in my application (with none working, obviously). In vulkanGraphicsStateGuardian.cxx, pCreateInfo->flags and pCreateInfo->subresourceRange.aspectMask are very clearly valid; any ideas why this might be happening?

**Comment by rdb** [comment] 2017-12-14 16:12
None of these errors make any sense.  We're clearly setting `compareEnable` to `VK_FALSE` just before calling `vkCreateSampler`, for example.

Can you run pview successfully?  I wonder if something in the linking is going wrong and you're somehow linking to a binary incompatible version that somehow has subtly different struct definitions.

I installed 1.0.65.1 and couldn't reproduce anything like what you're seeing.  (However, I did find a different couple of errors that I have pushed a fix to, along with a merge from master.)

**Comment by nosyliam** [comment] 2017-12-14 18:53
It might be because I just merged all the changes on the vulkan branch into my custom panda build which could be outdated. Are there any other sources outside of the Vulkan branch that might be causing this issue? 

I'll also go through the object files through IDA to see if everything is valid.

**Comment by rdb** [comment] 2017-12-14 19:13
No, I don't see how that could be an issue, unless you somehow pulled a very outdated version of the Vulkan branch.  The `vulkandisplay` directory is isolated code and other branches shouldn't be interfering.

**Comment by nosyliam** [comment] 2017-12-14 19:32
I think I know what might be wrong. If I remember correctly, makepanda.py for Vulkan links to Lib\vulkan-1.lib while my linker links to Lib32\vulkan-1.lib. Will see what happens.

**Comment by rdb** [comment] 2017-12-14 19:40
That sounds remotely plausible in that a 32-bit version would have a different struct layout than a 64-bit version, but I find it very strange why it would allow you to link to a library with a mismatching architecture to begin with, and why it wouldn't immediately crash upon attempting to run the resulting binary.

**Comment by nosyliam** [comment] 2017-12-15 03:35
I've checked out EVERYTHING and it still doesn't work. I've even took the liberty to go through the compiled .obj with IDA which shows stuff like this:
![image](https://user-images.githubusercontent.com/9064955/34025587-7c20f4b2-e105-11e7-8053-15f016c007d9.png)
Compare that to the code:
```
VkRenderPassCreateInfo pass_info;
pass_info.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
pass_info.pNext = NULL;
pass_info.flags = 0;
pass_info.attachmentCount = _depth_stencil_format ? 2 : 1;
pass_info.pAttachments = attachments;
pass_info.subpassCount = 1;
pass_info.pSubpasses = &subpass;
pass_info.dependencyCount = 0;
pass_info.pDependencies = NULL;

VkRenderPass pass;
VkResult
err = vkCreateRenderPass(vkgsg->_device, &pass_info, NULL, &pass);
```

I've also checked the executable too, it all checks out. I have reason to suspect that it's the libraries themselves. Where should I get the Vulkan libraries from? Compiling them myself isn't an option as VS 2010 isn't supported.

**Comment by rdb** [comment] 2017-12-15 17:14
I use the official Vulkan SDK from LunarG.

Well, let's try to narrow down the issue: can you build the SDK in normal, dynamic mode, and run pview.exe?  If that works, then we know that the Vulkan renderer works at all and we can further narrow it down.  If it doesn't, then you should try to run tools like vulkaninfo to try and find out whether you can run *any* Vulkan application.

**Comment by nosyliam** [comment] 2017-12-16 03:59
I feel like such an idiot: it was only when I was debugging the program in VS that I saw it was still using DLLs from Vulkan 1.0.65.1 while I was compiling with Vulkan 1.0.49.0. Everything works fantastic now -- I just don't have shader, though. Do you perhaps have a default shader I could use?

**Comment by rdb** [comment] 2017-12-16 20:17
OK, here goes:
http://rdb.name/vert.spv
http://rdb.name/frag.spv
Place these anywhere on the model-path.

It's a simple shader that only supports a single texture.  It uses push constants to get the color scale and modelview-projection matrix in because uniform buffers aren't yet implemented.  And the VulkanGSG hardcodes the data bindings because there's no shader reflection code yet or any code to use that to build pipeline layouts.  (I do have local work that enables reflection of SPIR-V shaders, but haven't gotten around to cleaning it up yet.)

**Comment by nosyliam** [comment] 2017-12-17 07:48
Everything works, but since alpha maps aren't supported stuff like this happen:
![image](https://user-images.githubusercontent.com/9064955/34077538-5c25cff4-e2bb-11e7-9d50-205bf0cc9fd5.png)

I have no idea how shaders work, so if you had any shaders that supported textures & alpha maps or at least had the GLSL source so I could (attempt) to fix them that would be great.

**Comment by theclashingfritz** [comment] 2017-12-18 03:58
I would just leave Alpha maps out as a non-inclusion if necessary. On a side not nice bear.

**Closed** 2017-12-19 16:54 UTC
Labels: vulkan

**Comment by rdb** [comment] 2017-12-19 16:55
Closing because the original issue is resolved.

I suggest you check back after basic support for SPIR-V reflection is supported, which would be required for any fancier shaders than the crude one that I have shared.
