### ISSUE TITLE
Incorrect surface point for collision between sphere and edge of polygon

### ISSUE THREAD

**Issue by fireclawthefox** [panda3d/panda3d#907] opened 2020-04-12 16:58 UTC
The surface point and probably also contact position and interior point got from a collision entry between a sphere and the edge of a polygon solid is incorrect for its X and Y values. In the below attached test case, the X-value at the time of contact is 0 but should be at around -0.4 according to the setup of the edge and the positioning of the sphere.

```
from direct.showbase.ShowBase import ShowBase
from panda3d.core import (
    CollisionTraverser,
    CollisionNode,
    CollisionSphere,
    CollisionPolygon,
    Point3,
    )
from panda3d.physics import (
    PhysicsCollisionHandler,
    ActorNode,
    ForceNode,
    LinearVectorForce,
    )

base = ShowBase()

#
# SETUP
#
# enable physics
base.enableParticles()

# setup default gravity
gravityFN = ForceNode("world-forces")
gravityFNP = render.attachNewNode(gravityFN)
gravityForce = LinearVectorForce(0, 0, -9.81/10)  # gravity acceleration
gravityFN.addForce(gravityForce)
base.physicsMgr.addLinearForce(gravityForce)

# Add the edge shaped polygon obect
base.contact_edge_x = -0.4
points = [
    Point3(base.contact_edge_x, 2, -3),
    Point3(base.contact_edge_x, -2, -3),
    Point3(base.contact_edge_x-2, -2, -3),
    Point3(base.contact_edge_x-2, 2, -3)]
p = list(reversed(points))
level = render.attachNewNode(CollisionNode("Level"))
level.node().addSolid(CollisionPolygon(p[0],p[1],p[2],p[3]))
level.node().addSolid(CollisionPolygon(p[3],p[2],p[2] - (0, 0, 2), p[3] - (0, 0, 2)))
level.show()

# Setup character
my_actor_node = ActorNode("playerPhysicsController")
my_actor_node.getPhysicsObject().setMass(210)
base.my_main_node = render.attachNewNode(my_actor_node)
base.my_main_node.setZ(-1)
base.physicsMgr.attachPhysicalNode(my_actor_node)

# main character sphere
r = 0.46575
my_char_collision_np = base.my_main_node.attachNewNode(CollisionNode("charBody"))
my_char_collision_np.node().addSolid(CollisionSphere(0, 0, r, r))
my_char_collision_np.show()

# Add our handler
my_physics_pusher = PhysicsCollisionHandler()
my_physics_pusher.addInPattern('%fn-in')
my_physics_pusher.addOutPattern('%fn-out')
my_physics_pusher.addCollider(my_char_collision_np, base.my_main_node)

# setup the traverser
base.cTrav = CollisionTraverser("base collision traverser")
base.cTrav.addCollider(my_char_collision_np, my_physics_pusher)
base.cTrav.showCollisions(render)

# setup Camera
base.disableMouse()
base.cam.setY(-5)
base.cam.setZ(-2.8)

#
# ACTION
#
def checkInBodyContact(collision):
    print("surface Point :", collision.getSurfacePoint(render))
    print("surface Normal:", collision.getSurfaceNormal(render))
    print("Contact Point :", collision.getContactPos(render))
    print("Interior Point:", collision.getInteriorPoint(render))
    print("time          :", collision.getT())
    intersection_point = collision.getSurfacePoint(render)
    print(base.my_main_node.getPos())

def reset():
    base.my_main_node.setPos(0,0,-1)

base.accept("charBody-in", checkInBodyContact)
base.accept("r", reset)

base.run()
```

**Comment by rdb** [comment] 2020-05-05 14:38
While fixing the surface point, I discovered that this is not actually what is causing your sphere not to slide off the corner.  That was actually caused by a different bug, namely that if the sphere lands right under the edge of the horizontal polygon, it erroneously reports a collision with that polygon, causing it to be pushed back up.  That is fixed in ed733942759cf794e92cae2d0a0479be06796e6d, which will be in 1.10.7.

I am still inclined to fix the erroneous surface point, however.  It will make the test slightly slower but will produce a more expected result.

**Closed** 2020-05-05 15:08 UTC
Labels: bug
