### ISSUE TITLE
Feature request: Shaders and shader inputs in bam files

### ISSUE THREAD

**Issue by wezu** [panda3d/panda3d#408] opened 2018-10-05 14:36 UTC
Shaders and shader inputs should be kept when writing (and later reading) bam files

**Comment by xordspar0** [comment] 2019-11-16 02:01
@wezu This looks like a quick note, but maybe you have (or used to have) some more context on this issue. Are there any more details you could provide (maybe source code files or functions to look at) that would help make it so anyone could drop by and pick this up?

**Comment by rdb** [comment] 2019-11-16 19:25
I think it is best to address support for serialisation of shaders as part of the shader pipeline overhaul.

**Comment by rdb** [comment] 2022-10-24 12:33
Closing as duplicate of #1381

**Closed by rdb** 2022-10-24 12:33 UTC
Labels: enhancement
