### ISSUE TITLE
Deploy-ng: Build fails, attempting to find "panda3d" in the third-party directory

### ISSUE THREAD

**Issue by ArsThaumaturgis** [panda3d/panda3d#676] opened 2019-06-20 23:54 UTC
I'm attempting to build a distributable app using a pre-release version of Panda3D via the following "requirements.txt":
```text
--pre --extra-index-url https://archive.panda3d.org/branches/master
panda3d
```

It fails, with the following appearing to be the relevant error message:
(Full error output at the end of the post.)
```text
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://archive.panda3d.org/thirdparty/panda3d/
```

I'm guessing that this is related to a recent "deploy-ng" commit that added the URL of the "thirdparty" directory to "pypi_extra_indexes".

The full error output:
```text
running bdist_apps
running build_apps
Building platforms: manylinux1_x86_64,win32,win_amd64
Gathering wheels for platform: manylinux1_x86_64
Collecting panda3d (from -r /home/thaumaturge/Documents/My Game Projects/KeyMapperTest2/requirements.txt (line 2))
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/download.py", line 198, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://archive.panda3d.org/thirdparty/panda3d/
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    'win_amd64'
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/commands.py", line 1358, in run
    self.run_command('build_apps')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/commands.py", line 364, in run
    self.build_runtimes(platform, True)
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/commands.py", line 497, in build_runtimes
    wheelpaths = self.download_wheels(platform)
  File "/home/thaumaturge/.local/lib/python3.6/site-packages/direct/dist/commands.py", line 420, in download_wheels
    subprocess.check_call([sys.executable, '-m', 'pip'] + pip_args)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'download', '-d', '/home/thaumaturge/Documents/My Game Projects/KeyMapperTest2/build/__whl_cache__', '-r', '/home/thaumaturge/Documents/My Game Projects/KeyMapperTest2/requirements.txt', '--only-binary', ':all:', '--platform', 'manylinux1_x86_64', '--abi', 'cp36m', '--extra-index-url', 'https://archive.panda3d.org/branches/master/opt', '--extra-index-url', 'https://archive.panda3d.org/thirdparty']' returned non-zero exit status 2.

```

**Comment by Moguri** [comment] 2019-08-29 17:12
@rdb As a heads up, this seems similar/related to the issue brought up in Discord where build_apps was looking on archive.panda3d.org for `pillow` and failing.

**Comment by Moguri** [comment] 2019-09-03 01:25
I am unable to reproduce this by modifying the asteroids sample to have the same requirements.txt as the one described in the issue.

**Comment by ArsThaumaturgis** [comment] 2019-09-03 03:18
Ah, sorry about that--looking back to a related forum-thread, it looks like this issue is likely resolved.

See here: https://discourse.panda3d.org/t/1-10-3-directoptionmenu-broken/24875/11

I'll leave confirming and closing to you, to be on the safe side. (Especially as I'm not longer using that pre-release build, I believe.)

**Comment by rdb** [comment] 2019-09-03 07:19
Hmm, you were using Python 3.6, same as the person in Discord who also reported this.  I wonder if the bug is specific to that.

**Comment by ArsThaumaturgis** [comment] 2019-09-03 16:58
Hmm... The version of Python that I currently use for builds is 3.6.8, I believe--but then again I'm not specifying a particular build any more, pre-release or otherwise.

**Comment by Moguri** [comment] 2019-09-06 16:05
As a note to myself, we should test the asteroids sample with Pillow and Python 3.6. If I cannot reproduce it there, I will close this report.

**Comment by Moguri** [comment] 2019-09-07 02:40
I was not able to reproduce this using Python 3.6, so I am closing this. If someone is running into this issue (or similar ones), please provide a way to reproduce it.

**Closed by Moguri** 2019-09-07 02:40 UTC
Labels: bug, deployment
