### ISSUE TITLE
Serialization/Unserialization of BulletTriangleMeshShape causes assertion issue

### ISSUE THREAD

**Issue by Melan2001** [panda3d/panda3d#960] opened 2020-06-21 17:33 UTC
I am trying to serialize / unserialize BulletShape, generated by Blender and blend2bam:
1/ generate the shape 
2/ save and "bam" it and 
3/ load it and restore it on a BulletRigidBodyNode

1/ and 2/ are ok, but step 3 gives me "Assertion failed: shape != nullptr at line 346 of ...\build\panda\src\bullet\bulletBodyNode.cxx" when using with BulletTriangleMeshShape (i.e. using Blender physics "Mesh" shape).

This however works for other types of shape (e.g. Sphere).

Included:

- Source file
- Models (Suzanne)

[Sent_to.zip](https://github.com/panda3d/panda3d/files/4809938/Sent_to.zip)

**Comment by rdb** [comment] 2020-06-27 12:31
I ran your script and do not get an error message on the latest version of Panda3D 1.10.  Please make sure you are using the latest bugfix release of Panda3D or otherwise update your reproduction instructions.

**Comment by Melan2001** [comment] 2020-06-27 16:27
Many thanks rdb. 

I am using the official 1.10.6 build from March 2020 so unless you are using the master branch and there are some changes in the master related to this, I don't see it as the source of issue.

My instructions were probably not clear enough (sorry if that is the case) but have you tried to replace at line 39 from:
`self._model = base.loader.load_model("suzanne/model_sphere_shape.bam",noCache=True)` [works]
to:
`self._model = base.loader.load_model("suzanne/model_triangle_shape.bam",noCache=True)` [assertion issue] ?

Indeed, the issue lies with the "model_triangle_shape.bam" model and not with the "model_sphere_shape.bam" model. Simple shapes seem to work but not BulletTriangleMeshShape.

Thanks!

**Comment by rdb** [comment] 2021-01-02 10:35
Hi, the problem is that you need to call `bam_file.resolve()` after `bam_file.read_object()` to properly process all the nested pointers, or the object will be invalid.

**Closed by rdb** 2021-01-02 10:35 UTC
Labels: bullet
