### ISSUE TITLE
Headless gl + autoshader doesn't support shadows

### ISSUE THREAD

**Issue by Clockwork-Muse** [panda3d/panda3d#1154] opened 2021-04-19 21:08 UTC
## Description
When using the autoshader and headless gl, an error is thrown:
```text
:display:gsg:glgsg(error): Could not load program: created-shader (The profile is not supported.)
```
This error is produced regardless of the presence of lights in a scene, but any lights that would cast shadows are _ignored_, and show neither the light nor any shadows that should be generated.

![Untitled](https://user-images.githubusercontent.com/5569508/115303562-a1c10280-a118-11eb-9b39-2b0cfd0ec9cd.png)

## Steps to Reproduce
```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import AmbientLight, CardMaker, NodePath, Point3, Spotlight, Vec4, loadPrcFileData

class MyApp(ShowBase):
    def __init__(self):
        super().__init__(self)

        def create_light(position: Point3, target: Point3) -> NodePath:
            light = self.render.attach_new_node(Spotlight("Spot"))
            light.set_pos(position)
            light.look_at(target)
            self.render.set_light(light)

            light.node().set_shadow_caster(True, 1024, 1024)
            light.node().get_lens().set_near_far(.1, 100)
            light.node().get_lens().set_fov(70)

        self.spot_a = create_light(Point3(-5, 0, 5), Point3(5, 0, 0))

        self.ambient = self.render.attach_new_node(AmbientLight("Ambient"))
        self.ambient.node().set_color(Vec4(0.2, 0.2, 0.2, 1))
        self.render.set_light(self.ambient)

        floor_tex = self.loader.load_texture("/panda3d/models/maps/envir-ground.jpg")
        cm = CardMaker('')
        cm.set_frame(-5, 5, -5, 5)
        self.floor = self.render.attach_new_node(cm.generate())
        self.floor.set_p(-90)
        self.floor.set_texture(floor_tex)

        self.camera.set_pos(0, 0, 20)
        self.camera.look_at(0, 0, 0)
        self.disable_mouse()

        self.render.set_shader_auto()

def generate_synth():
    loadPrcFileData("",
    """
        gl-debug #t
        audio-library-name null
        window-type offscreen
        load-display p3headlessgl
    """)

    base = MyApp()
    base.graphicsEngine.renderFrame()
    base.screenshot(namePrefix="screenshot.png", defaultFilename=False)

generate_synth()
```

## Environment
 * Operating system: Ubuntu 20.04
 * Docker Container base: nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
 * System architecture: x86_64
 * Panda3D version: 1.10.9
 * Installation method: custom build, commit 69c6050fa88abf8a129657b8838be377cde8b13d for 1.10.9
 * Python version: 3.8.5

**Comment by RemiLacroix-IDRIS** [comment] 2021-06-07 13:48
Any news regarding this issue? We are also seeing it.

**Comment by rdb** [comment] 2021-07-02 13:54
Could you please try:
* Adding `sort=-1000` to the `set_shadow_caster` call
* Adding extra calls to `render_frame()`

**Comment by Clockwork-Muse** [comment] 2021-07-07 18:06
> Adding `sort=-1000` to the `set_shadow_caster` call
> Adding extra calls to `render_frame()`

No change.  Still spits out the error, still no lights/shadows.  
Modifying it to output frames in an update task also doesn't change anything (other than the first frame being black).

**Comment by rdb** [comment] 2021-08-11 07:14
Duplicate of #1150

**Closed by rdb** 2021-08-11 07:14 UTC
