### ISSUE TITLE
Loading Texture from PNMImage fails if its width or height is bigger than 2^14

### ISSUE THREAD

**Issue by Epihaius** [panda3d/panda3d#306] opened 2018-04-21 13:59 UTC
Some use-case info:
as part of my attempt to create a pure-Panda GUI for my Panda3D Studio project, I implement a scrollable pane as a card to which a texture with a much larger "virtual" size is applied, with the appropriate texture scale; scrolling is accomplished by simply changing the texture offset.
The texture itself is loaded from a procedurally created PNMImage, into which the images representing the different widgets are copied/blended.

The entire system works nicely, as long as the PNMImage doesn't become too large: as soon as its width or height gets bigger than 2^14 pixels, a call to `Texture.load(pnm_image)` has no visible effect even though its return value of `True` indicates success; the current contents of the texture remains unchanged, although a call to `Texture.get_x_size()`/`get_y_size()` does return the width/height of the new PNMImage.

Code sample to reproduce this issue:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)
        cm = CardMaker("card")
        cm.set_frame(0, 500, -300, 0)
        self._card = card = self.pixel2d.attach_new_node(cm.generate())
        self._tex = tex = Texture("card_tex")
        # deliberately give the image a height bigger than 2^14, so loading it into tex will
        # fail, yielding a white card
        img = PNMImage(10, 2 ** 14 + 1, 4)
        img.fill(1., 0., 0.)  # the card should appear red
        img.alpha_fill(1.)
        tex.load(img)
        card.set_texture(tex)
        print("The card should now be red.")
        self.taskMgr.do_method_later(1., self.__load_green_image, "load_green_image")
        self.taskMgr.do_method_later(2., self.__load_blue_image, "load_blue_image")

    def __load_green_image(self, task):

        img = PNMImage(10, 2 ** 14, 4)
        img.fill(0., 1., 0.)  # the card should appear green
        img.alpha_fill(1.)
        self._tex.load(img)
        print("The card should now be green.")

    def __load_blue_image(self, task):

        img = PNMImage(10, 2 ** 14 + 10, 4)
        img.fill(0., 0., 1.)  # the card should appear blue
        img.alpha_fill(1.)
        self._tex.load(img)
        print("The card should now be blue.")


app = MyApp()
app.run()
```

Running the above code should initially show a white card (while it should be red), that turns green after a second and keeps that color, although another second later it should have turned blue.

Explicitly setting the texture format to something like `F_rgba32` didn't make a difference.
Writing the PNMImage to disk and having the texture read the resulting file does work, so it is not a limitation of the Texture class or my hardware.

Even if this is not really a bug, but rather some internally set "sane" size limit, it would be nice if at least a warning were displayed, or better yet, if `Texture.load(pnm_image)` returned `False` in such cases.

Tested with the recent version e6e39cc of Panda3D (Python 2.7, 64-bit) on Windows 10.

**Comment by rdb** [comment] 2018-04-30 23:15
The texture is actually loaded completely fine; the problem is that the texture exceeds the GPU's maximum supported texture height, and the GL renderer notices that and is trying to upload a downscaled version automatically, but there's a bug in that mechanism that appears when the texture has mipmapping disabled.

I have checked in a fix. Thanks for reporting, and thanks for the helpful test case!

**Closed** 2018-04-30 23:14 UTC
Labels: bug

**Comment by Epihaius** [comment] 2018-05-02 17:09
Thank you for your work!

There is one last problem, though: the texture is quite blurry. But perhaps this is related to the downscaling you mentioned and just cannot be helped. 

Code:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)
        cm = CardMaker("card")
        cm.set_frame(0, 200, -300, 0)
        card1 = self.pixel2d.attach_new_node(cm.generate())
        card2 = self.pixel2d.attach_new_node(cm.generate())
        card2.set_x(210)
        self.__create_tex(card1, 2 ** 14 + 1)
        self.__create_tex(card2, 2 ** 14)

    def __create_tex(self, card, tex_height):

        img = PNMImage(200, tex_height, 4)
        img.fill(1., 1., 1.)
        img.alpha_fill(1.)
        painter = PNMPainter(img)
        painter.set_pen(PNMBrush.make_pixel((0., 0., 0., 1.)))

        for i in range(1, 10):
            painter.draw_line(20, tex_height - i * 20, 180, tex_height - i * 20)

        tex = Texture("card_tex")
        tex.set_minfilter(SamplerState.FT_nearest)
        tex.set_magfilter(SamplerState.FT_nearest)
        tex.load(img)
        card.set_texture(tex)
        card.set_tex_scale(TextureStage.get_default(), 1., 300. / tex_height)


app = MyApp()
app.run()
```

This leads to a blurry texture on the card to the left (with texture larger than 2^14 pixels in height) and a sharp texture on the card to the right (with texture equal to 2^14 pixels in height):

![blurry](https://user-images.githubusercontent.com/16452534/39537777-e3b45cd4-4e3a-11e8-965e-c49ac109407f.png)

I tried using `SamplerState.FT_nearest`, but to no avail.
If nothing can be done about this, I'll have to try to cut up the texture into parts smaller than 2^14 and swap them while scrolling.

**Comment by rdb** [comment] 2018-05-08 15:31
As stated, the problem occurs because the texture size exceeds the driver-reported limit.  Panda is uploading a half resolution version of the texture, so this is what you are seeing.

**Comment by Epihaius** [comment] 2018-05-09 14:37
OK, thank you for the explanation.

It shouldn't be a real problem to load different smaller parts of a PNMImage into the same texture and adjusting its offset and scale, based on the current scroll offset. Not to mention that this will be more memory-efficient anyway.
