### ISSUE TITLE
textNode generate() is slow

### ISSUE THREAD

**Issue by drewc5131** [panda3d/panda3d#216] opened 2017-12-23 19:56 UTC
I was looking at PSTATS and noticed that a big chunk of frame time when entering a new area is Generate Text. This is especially relevant in Toontown, where after it loads all the models, the game takes a while to create all the nametags and building signs. Loading into one area, the frame where you actually enter the area, takes about 100ms in showcode, where about 70% of that is by generating text.

**Comment by rdb** [comment] 2017-12-23 19:57
Which version of Panda are you using?  Panda 1.10 has gotten dramatic improvements in text generation performance.

**Comment by theclashingfritz** [comment] 2017-12-24 15:33
Even with the major improvements... I can't say it doesn't take forever when it does.

**Comment by drewc5131** [comment] 2017-12-24 15:35
@rdb I am currently using Panda 1.10, not the most recent version as i do not have a version of it with astron, but it is still 1.10

**Comment by rdb** [comment] 2017-12-24 15:38
Please make sure this PRC setting is set to ensure the improvements are active, and that it's not overridden anywhere to be false:
```
text-dynamic-merge 1
```

Also, you could try setting `text-flatten 0` which may further speed up text generation.

If these settings don't help, there must be something about your specific configuration that is causing it to be less efficient.  Please attach a test case reduced to the absolute minimum amount of code and models required for me reproduce this performance issue.

**Comment by theclashingfritz** [comment] 2017-12-24 15:44
HarfBuzz may help as well. I'd try tests with both it and FreeType.

**Comment by drewc5131** [comment] 2017-12-24 15:47
@theclashingfritz can you elaborate on what you mean?
@rdb They didnt seem to help too much.

**Comment by theclashingfritz** [comment] 2017-12-24 15:48
@drewc5131 Panda3D has support for https://www.freedesktop.org/wiki/Software/HarfBuzz/

**Comment by rdb** [comment] 2017-12-24 16:38
HarfBuzz won't help with performance.  Leave it off if you don't need it.

I'm going to need that test case since I don't have any other information to go on here.

**Comment by drewc5131** [comment] 2017-12-26 00:00
I can't really do a separate test case because this is something that's only really a problem with what Toontown requires, like having building names

**Comment by rdb** [comment] 2017-12-26 18:03
In order to do anything with this I will need a simple reproduction case.  You could create this by creating a simple program that only displays text in a way that your real application does.  Alternatively, it might be possible to debug this if you installed the pdbs for the build and created a dump from a sampling profiler (such as VS' built-in profiler), but it would be easier to just have a reproduction case.  Otherwise I will have no choice but to close this issue.

Thanks in advance!

**Comment by rdb** [comment] 2018-01-03 22:17
It may be easier to just dump the entire scene with text and all to a .bam file using writeBamFile, after all the text has been loaded into it, so that I will be able to profile the resulting bam file with pview.

**Comment by rdb** [comment] 2018-01-15 22:33
Could you follow up on this?  It should be straightforward to dump a scene to bam, with TextNodes and all, and it would really help me get to the root of why the new text generation code isn't achieving adequate performance in your application.  I can provide my e-mail address if you cannot post the scene publicly.

**Comment by theclashingfritz** [comment] 2018-01-15 23:04
I'll see if i can reproduce this and dump it to a .bam for you.

**Comment by theclashingfritz** [comment] 2018-01-16 00:23
I did a dump of a scene. I'm unsure if it contains the same issue but feel free to check it out anyways.

[TestCase.zip](https://github.com/panda3d/panda3d/files/1633276/TestCase.zip)

**Comment by rdb** [comment] 2018-01-16 20:24
There are no TextNodes in the attached bam file according to `bam-info -ls TestCase.bam`.  Please ensure that the bam file is generated after the text nodes are introduced into the scene.

**Comment by rdb** [comment] 2018-01-24 11:10
Could you please provide the requested information?  Either a test case, .bam file containing TextNodes, a specification of the settings and contents of the text in your scene so that we might be able to construct a test case, or anything that could provide some clues as to the nature of this bottleneck.  Does the text have any text properties applied?  Embedded graphics, perhaps?

Without any leads to go on, there's nothing we can do.  My own text rendering test cases don't exhibit this performance issue.

**Comment by rdb** [comment] 2018-02-14 19:20
Closing for now due to lack of response.  Unfortunate, since if there really still is a bottleneck in the text generation system, I would like to see it fixed.

**Closed by rdb** 2018-02-14 19:20 UTC
