### ISSUE TITLE
Unclear error: AssertionError: has_column()...

### ISSUE THREAD

**Issue by iljah** [panda3d/panda3d#1672] opened 2024-07-21 14:35 UTC
## Description

Spent some time trying to understand why I was getting this:
```
Traceback (most recent call last):
  File "...py", line 7, in <module>
    color.addData4(0, 0, 0, 0)
AssertionError: has_column() at line 888 of built1.10/include/geomVertexWriter.I
```
Turns out I should've used `GeomVertexFormat.getV3c4t2()` instead of `GeomVertexFormat.getV3t2()`. Error like this would've been much clearer:
```
Error: No column for color in vertex data.
```

## Steps to Reproduce

```
#! /usr/bin/env python3
from panda3d.core import *
gvd = GeomVertexData('', GeomVertexFormat.getV3t2(), Geom.UHStatic)
color = GeomVertexWriter(gvd, 'color')
color.addData4(0, 0, 0, 0)
```

## Environment
 * Operating system: fedora 40
 * System architecture: x86_64
 * Panda3D version: 1.10.14
 * Installation method: pip3
 * Python version (if using Python): 3.12.4

**Comment by rdb** [comment] 2024-08-04 20:52
Thanks for reporting this. I appreciate that it's not trivial to the untrained eye to interpret the meaning of these assertion errors. I'm actually going to consider this a duplicate of #966, as it fits within a general pattern of assertion errors that should be replaced with more helpful exceptions or error messages.

Duplicate of #966

**Closed by rdb** 2024-08-04 20:52 UTC
Labels: usability
