### ISSUE TITLE
loadModel loads the model but not the texture.

### ISSUE THREAD

**Issue by Guidane** [panda3d/panda3d#1411] opened 2022-12-22 12:09 UTC
Hi.

loadModel apears to have some trouble loading textures when a path with double backslashes is used.
when a path like this is used "root\\\assets\\\modelname" it will load the model, but it wont load the texture
when a path like this is used "root/assets/modelname" it loads both model and texture without problems.

**Comment by git2323** [comment] 2022-12-22 13:01
You can take a look at the documentation for the supported filenames and ways to convert them: [https://docs.panda3d.org/1.10/python/programming/advanced-loading/filename-syntax](url) Hope that helps.

**Comment by rdb** [comment] 2022-12-22 15:32
Working version of above link:
https://docs.panda3d.org/1.10/python/programming/advanced-loading/filename-syntax

Closing as not a bug.

**Closed by rdb** 2022-12-22 15:32 UTC
