### ISSUE TITLE
Add per color attachment blend enabling

### ISSUE THREAD

**Issue by el-dee** [panda3d/panda3d#1271] opened 2022-02-23 21:01 UTC
## Description

Currently blending is enabled on all the color buffers, when using `ColorBlendAttrib` or `TransparencyAttrib` using `glEnable(GL_BLEND)` followed by the actual blending equation configuration. However, since OpenGL 3, OpenGL allows to enable blending on individual color buffers using `glEnablei(GL_BLEND, index)` (and I believe a couple of other color related features).

I'm not sure how this could be added, perhaps as an additional parameter on the `FramebufferProperties` object, or as an extre flag on `render_to_texture()` ?

## Use Case

My main use case is for generating precomputed data that need to be iteratively created (namely atmospheric scattering), the results of a previous iteration is stored in one (or more) attachment while the final result is accumulated in another attachment. The current workaround is to calculate the delta in a first stage (with blending deactivated) then accumulate the result in a second stage (with additive blending enabled).
Also I can not use compute shaders for that purpose as they are not supported on macOS.

A second use case is to perform color picking of objects. If blending is enabled, the index stored in the picking buffer is blended with the index of any background object, which make the technique unusable. My current workaround is to use `imageStore()` but again it is not supported on macOS...

**Comment by rdb** [comment] 2022-02-23 21:03
Duplicate of  #338

**Closed** 2022-02-23 21:20 UTC
Labels: enhancement
