### ISSUE TITLE
threading-model cull/draw: crash on base.setFrameRateMeter(False)

### ISSUE THREAD

**Issue by kamgha** [panda3d/panda3d#427] opened 2018-10-20 23:10 UTC
I'm on Windows 7, Python 3.7:

When the `threading-model` is set to anything but the default empty (e. g. `cull/draw`), a call to `base.setFrameRateMeter(False)` or `base.setSceneGraphAnalyzerMeter(False)` will result in a crash.

Sample code:

```
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase

loadPrcFileData("", "threading-model cull/draw")        # uncomment this


class FPSTest(ShowBase):

    def __init__(self):
        ShowBase.__init__(self)

        self.accept('1', self.show_fps)
        self.accept('2', self.hide_fps)

    def show_fps(self):
        base.setFrameRateMeter(True)

    def hide_fps(self):
        base.setFrameRateMeter(False)


app = FPSTest()
app.run()
```

**Comment by xseano** [comment] 2018-10-22 04:12
Can you detail what kind of crash you get?

I tested your code sample and got a segmentation fault when trying to disable the frame meter. The segfault could be from a variety of things, but given that cull/draw is a 3-stage pipeline, it could be that there's some error when it tries to access memory space during the first stage.

Alternatively, the default works single-threaded.

**Comment by xseano** [comment] 2018-10-22 04:12
Can you detail what kind of crash you get?

I tested your code sample and got a segmentation fault when trying to disable the frame meter. The segfault could be from a variety of things, but given that cull/draw is a 3-stage pipeline, it could be that there's some error when it tries to access memory space during the first stage.

Alternatively, the default works single-threaded.

**Comment by xseano** [comment] 2018-10-22 04:12
Can you detail what kind of crash you get?

I tested your code sample and got a segmentation fault when trying to disable the frame meter. The segfault could be from a variety of things, but given that cull/draw is a 3-stage pipeline, it could be that there's some error when it tries to access memory space during the first stage.

Alternatively, the default works single-threaded.

**Comment by xseano** [comment] 2018-10-22 04:15
Can you detail what kind of crash you get?

I tested your code sample and got a segmentation fault when trying to disable the frame meter. The segfault could be from a variety of things, but given that cull/draw is a 3-stage pipeline, it could be that there's some error when it tries to access memory space during the first stage.

Alternatively, the default works single-threaded.

**Comment by xseano** [comment] 2018-10-22 07:19
Can you detail what kind of crash you get?

I tested your code sample and got a segmentation fault when trying to disable the frame meter. The segfault could be from a variety of things, but given that cull/draw is a 3-stage pipeline, it could be that there's some error when it tries to access memory space during the first stage.

Alternatively, the default works single-threaded.

**Comment by kamgha** [comment] 2018-10-22 11:57
@xseano It is exactly what you describe: A segfault when trying to disable the frame rate meter. The single-threaded mode works fine.

**Comment by rdb** [comment] 2018-10-22 13:48
This seems to be due to the DisplayRegion being destroyed but only removed from the window in the first pipeline stage, whereas other pipeline stages can still reference it.  I have a fix for this prototyped, although I think the root problem here is that the total list of DisplayRegions on GraphicsOutput is not pipeline cycled.

**Comment by xseano** [comment] 2018-10-22 16:14
@rdb 

I fixed this by obtaining the DisplayRegion object and using `setActive(False)` to stop it from rendering, but not fully destroying it with `clearWindow()` so I can access it again when I press "1" in this instance.

Example:

```python
    def setFrameRateMeter(self, flag):
        """
        Turns on or off (according to flag) a standard frame rate
        meter in the upper-right corner of the main window.
        """
        if flag:
            if not self.frameRateMeter:
                self.frameRateMeter = FrameRateMeter('frameRateMeter')
                self.frameRateMeter.setupWindow(self.win)
        else:
            if self.frameRateMeter:
                displayRegion = self.frameRateMeter.getDisplayRegion()
                displayRegion.setActive(False)
                #self.frameRateMeter.clearWindow()
                self.frameRateMeter = None
```

**Comment by xseano** [comment] 2018-10-22 16:15
Similarly...

```python
    def setSceneGraphAnalyzerMeter(self, flag):
        """
        Turns on or off (according to flag) a standard frame rate
        meter in the upper-right corner of the main window.
        """
        if flag:
            if not self.sceneGraphAnalyzerMeter:
                self.sceneGraphAnalyzerMeter = SceneGraphAnalyzerMeter('sceneGraphAnalyzerMeter', self.render.node())
                self.sceneGraphAnalyzerMeter.setupWindow(self.win)
        else:
            if self.sceneGraphAnalyzerMeter:
                displayRegion = self.sceneGraphAnalyzerMeter.getDisplayRegion()
                displayRegion.setActive(False)
                #self.sceneGraphAnalyzerMeter.clearWindow()
                self.sceneGraphAnalyzerMeter = None
```

**Comment by treamology** [comment] 2018-10-23 19:03
@xseano Would it not be more advantageous to fix the root issue, which is not being able to destroy/remove DisplayRegions, instead of just patching these two instances of the issue?

**Comment by xseano** [comment] 2018-10-23 22:29
@treamology 

That's a good point, I'll be sure to push all updates to respective PR @ https://github.com/panda3d/panda3d/pull/430

**Closed** 2018-10-28 10:56 UTC

**Comment by rdb** [comment] 2018-10-28 11:18
I fixed the root cause of this in the C++ code.  Panda3D now no longer crashes when removing a DisplayRegion while another pipeline stage might still be at it; this is done by removing it from the "active display region" list on all pipeline stages, instead of just the current one.

It does mean that effectively, you're removing it from the previous frame, not the next one, so the hiding of the frame rate meter will take immediate effect whereas the showing will follow the flow of the pipeline.  I don't know that this is an issue, but if it is, there's a slightly more complicated fix that we could probably make by making sure that display regions are preserved until the last pipeline stage is done with it.
