### ISSUE TITLE
Texture loading issues

### ISSUE THREAD

**Issue by derpydraggo** [panda3d/panda3d#1354] opened 2022-08-13 08:52 UTC
## Description

I'm working on a project that uses Panda3D for the engine. Upon pulling changes since commit d7717727e7f32148b4a7f3a3075d1ac75b33c1ae and building from source, our project noticed that after running our game for a bit, textures would end up looking off, as if we were using low-res textures. I was also able to reproduce something similar in [Roaming Ralph](https://drive.google.com/file/d/1r6otjrlxVFjKCtSm3XHYsOPnJ1OJ9SMD/view?usp=sharing). Before our project pulled the latest changes, this issue would only happen rarely, if at all.

## Steps to Reproduce
The easiest way to reproduce this is to edit `main.py` for the Roaming Ralph sample, and adding the following lines to the top of the file:
```python
from panda3d.core import loadPrcFileData
loadPrcFileData('', 'graphics-memory-limit 1048576') # use any small value here to speed up the reproduction of the bug
```
After doing that, run Roaming Ralph, and start moving Ralph and the camera around a bit (in such a way that the trees and boulders are no longer in scene, then reloaded into it).

## Environment
 * Operating system: Any
 * System architecture: Any
 * Panda3D version: 1.11.0
 * Installation method: built from source
 * Python version (if using Python): Any
 * Compiler (if using C++): Any

**Comment by tyteen4a03** [comment] 2022-10-27 23:23
Hiya, just wondering if you've had a chance to look into this? :)

**Comment by rdb** [comment] 2022-10-28 10:51
Is there anything that indicates this is not working as intended? If you're going to tell Panda that you have only 1 MB of VRAM, it's going to unload your textures at the first opportunity and reload them in a lower quality.

**Comment by rdb** [comment] 2022-10-28 10:57
Ah, Panda is failing to reload the texture from disk for some reason, so it's uploading the simple stand-in version of the textures. Setting `keep-texture-ram` in Config.prc will work around this issue, at cost of increased CPU RAM use.

**Comment by rdb** [comment] 2022-10-28 11:15
Ah, it's a regression with the asynchronous texture reloading system: it will reload the texture once, but not twice.

Another way to work around it is by using `allow-incomplete-render true`, which will ensure that you never see a low-quality texture, at expense of framerate chugs when textures are reloaded.

Fix will be in master shortly.

**Closed** 2022-10-28 11:19 UTC
Labels: regression
