### ISSUE TITLE
recent eggSaver update broke egg2bam

### ISSUE THREAD

**Issue by sean5470** [panda3d/panda3d#237] opened 2018-01-24 22:06 UTC
The most recent eggSaver update seems to have broken, at least bam2egg, once again. I included what seems to be happening in the readme.txt file that is in the attached zip archive. The archive also contains all the files needed to see what is happening with it. I've included the original bam files, the textures and the egg files converted from both, the previous eggSaver revision, and the latest revision.

**Comment by rdb** [comment] 2018-01-26 16:04
Seems that this was a regression caused by dee4cd62017853f44bb54f6e6c764ba2b18cf90f which broke geometry attached to exposed joints.  The main problem with that commit is that it makes too many assumptions about how the .bam file was generated to begin with.

I'll work on a fix.  Note that the original also didn't convert it correctly, since it duplicated many nodes unnecessarily and it also looks like it didn't preserve exposed joints (so some geometry may not have animated with the model correctly).

**Comment by sean5470** [comment] 2018-01-26 17:29
Sounds like a plan. Thanks for all the help and everything you do!

**Comment by theclashingfritz** [comment] 2018-03-16 14:18
bump

**Comment by Moguri** [comment] 2018-12-09 01:02
@rdb Should this be added to the 1.10 milestone since it is a regression?

**Comment by rdb** [comment] 2018-12-31 16:10
I'm reverting that commit for now, and closing this bug, but please note that you cannot post protected IP on the GitHub tracker unless you have obtained permission to redistribute these files, so I've edited out the link from your issue report.

**Closed** 2018-12-31 16:11 UTC
Labels: regression
