### ISSUE TITLE
dcparser fails to compile outside of panda

### ISSUE THREAD

**Issue by ksmit799** [panda3d/panda3d#944] opened 2020-06-01 10:03 UTC
The dcparser is designed to be compiled outside of panda to be used as either apart of a program or as an external library. Over the years however, that functionality has been somewhat neglected and it no longer compiles out of the box. While this isn't a high priority issue, it would be nice to get that functionality back. The issues that I've come across are as follows:

Extension code needs to be wrapped in a WITHIN_PANDA preprocessor directive:
```python
EXTENSION(void pack_object(PyObject *object));
```

dcLexer.lxx includes `pstrtod.h` which is a panda specific header file. It's used when calling `patof();` in the following block of code:
```python
{REALNUM} {
  // A floating-point number.
  accept();
  dcyylval.u.real = patof(dcyytext);
  dcyylval.str = dcyytext;
  return REAL;
}
```

The prebuilt dcLexer.lxx and dcParser.yxx uses a `#line` preprocessor directive that uses the full path to the respective file, which requires the source tree outside of the dcparser folder to be kept intact:
```cpp
#line 1 "direct/src/dcparser/dcLexer.lxx"
#line 7 "direct/src/dcparser/dcParser.yxx"
```
Should instead be:
```cpp
#line 1 "dcLexer.lxx"
#line 7 "dcParser.yxx"
```
This used to not contain the full path, however when rebuilt in e4f493b872c16f6b242db29a654db2c898f06fb3 it changed to using the full path.

**Comment by ksmit799** [comment] 2020-06-01 10:05
The extension issue has been fixed in 862c0b804bc1f71b5bbc13b8817029f3f076db65

Not sure what to do about the `pstrtod.h` issue.

**Comment by rdb** [comment] 2020-06-01 10:08
Linking #759 for reference.  This is a duplicate of that issue but we can continue the discussion in this one.

It sounds like we will need to add these two lines to dcbase.h if WITHIN_PANDA is not defined:
```
#define patof(x) atof(x)
#define EXTENSION(x)
```
Feel free to try it and make a PR if it works.

I'm not sure what problem you think the `#line` change is causing?  It should only affect compiler-generated error messages.

**Comment by rdb** [comment] 2020-06-27 12:16
Closing as #945 was merged.

**Closed by rdb** 2020-06-27 12:16 UTC
