### ISSUE TITLE
Access Violation when logging to file

### ISSUE THREAD

**Issue by thetestgame** [panda3d/panda3d#319] opened 2018-05-11 15:10 UTC
The following code produces a access violation after writing to the out.txt file. 
```python
nout = MultiplexStream()
Notify.ptr().setOstreamPtr(nout, 0)
nout.add_file(Filename('out.text'))
```

This exact code can be found as an example on the manual page for Log Messages https://www.panda3d.org/manual/index.php/Log_Messages

The PRC config for this same functionality does not work either
```
notify-output mygame-log.txt
```

I am currently uses the latest Panda3d built for Python 3 off the repository.

**Comment by thetestgame** [comment] 2018-05-14 14:00
I'm using the latest commit on the repository as of 5/12/2018 with Python 3. Far as settings go I left it all default.

**Comment by JoelStienlet** [comment] 2018-05-19 10:59
Hello @thetestgame,
you can adjust the logging level with:
`notify.setSeverity(NSInfo)`

**Comment by thetestgame** [comment] 2018-05-20 15:32
Adjusting the severity does not solve the issue with it not logging to file.

**Comment by JoelStienlet** [comment] 2018-05-21 09:33
I'm still very new at Panda3D. I did some tests, here's a minimal code that does both logging on the standard output and in a file:
`from direct.showbase.ShowBase import ShowBase
from panda3d.core import *

nout = MultiplexStream()
nout.add_file(Filename('out.text'))
nout.addStandardOutput()
Notify.ptr().setOstreamPtr(nout, 0)
Notify.ptr().writeString('hello world!')`

**Comment by Moguri** [comment] 2019-03-03 01:39
@rdb can you please check to see if there are any usage issues with @thetestgame's last sample? Without any more information, I would consider the crash as "could not reproduce."

**Comment by rdb** [comment] 2020-06-27 12:50
Oops, looks like I missed the further activity on this issue.

@thetestgame the DirectNotify system isn't the same thing as Panda's C++ Notify system.  DirectNotify does not respect the C++ Notify output stream nor the notify level, which is controlled using a separate `default-directnotify-level` variable.

It seems unrelated to the issue reported in your original post.  Does it still occur?  I cannot reproduce it.  Could it be that the MultiplexStream object was going out of scope?  You need to store it somewhere as ostream/istream objects aren't reference-counted.

**Comment by rdb** [comment] 2022-12-09 14:05
No further activity on this issue in over two years, so I'm closing it.  I'm going to guess that the original issue was the same as #1371, which can be kept open.

**Closed by rdb** 2022-12-09 14:05 UTC
Labels: bug
