### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [panda3d/panda3d#935] opened 2020-05-05 12:25 UTC
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [InkblotVideoCursor](https://github.com/panda3d/panda3d/blob/371e60c768cfd1a1383c5b05f1cab2078014ccea/panda/src/movies/inkblotVideoCursor.cxx#L47)
- [MayaToEggServer](https://github.com/panda3d/panda3d/blob/5f7809469c04047b64b2b998c8251239a826c9df/pandatool/src/mayaprogs/mayaToEgg_server.cxx#L162)

**Comment by rdb** [comment] 2020-05-05 12:32
I'm not opposed to it, but I'm not going to spend time on it unless we are aware of an actual problem that is solved by doing so.

If you want to make a PR, you are welcome to do so.  Do note that I'm generally not inclined to accept these kinds of refactors on code that does not have adequate unit test coverage, so that we are more confident that we are not introducing regressions.  So if you do make a PR, I would highly encourage you to add unit tests.

Not sure what "exception safety" means in the context of Panda, since (like most game industry middleware) we do not compile Panda with C++ exceptions enabled.

**Comment by rdb** [comment] 2020-06-27 12:18
Closing this to prevent it from cluttering up the open issue list, since it is not a priority.

**Closed by rdb** 2020-06-27 12:18 UTC
Labels: cleanup
