### ISSUE TITLE
Lights do not transition or move if they are in a model nodetree instead of an actor nodetree

### ISSUE THREAD

**Issue by SkyLeach** [panda3d/panda3d#284] opened 2018-03-18 16:37 UTC
Branch I'm using is master at adbab8deae333f735a7fde44f464833dd437c914

Nothing I try will move a light attached to a model node.

I'm creating this hook and creating a UnitTest for the scenario now.

**Comment by SkyLeach** [comment] 2018-03-18 21:44
Ok, I duplicated the walking panda scene from the manual.

https://gist.github.com/SkyLeach/5eaea2a75d6de4fd14ef24566a101707

According to the manual a node (including a light Node) should transition with the parent Node [NodePath.attachNewNode](https://www.panda3d.org/reference/devel/python/classpanda3d.core.NodePath#a5d63275fa85732352d5df404eacb18bb)

However calling [NodePath.setLight](https://www.panda3d.org/reference/devel/python/classpanda3d.core.NodePath#ae9b53e6894e0a6c4c0e5712c6add6eac), which is supposed to set which sections of the scenegraph are affected by a light, the result is similar to calling [reparentTo](https://www.panda3d.org/reference/devel/python/classpanda3d.core.NodePath#a28bf3cad2dba5aa415ea6e64ea8a73b8) and moved the entire nodepath rather than just setting which nodes are affected by the light.  The lights position is changed, and translations on the light's parent no longer have any effect.

The NodePath, however, is not changed.

The attached Gist will print the positions with getPos for both itself and it's parent if you pass it an option of --debug for each of it's 3 enabled test scenarios.

**Comment by SkyLeach** [comment] 2018-04-20 17:51
I updated the gist code (flake8 cleanup) and added a log file.

[view both here](https://gist.github.com/SkyLeach/5eaea2a75d6de4fd14ef24566a101707) (same gist link)

**Comment by montreal91** [comment] 2018-09-21 06:27
@SkyLeach, is this issue still actual?

**Comment by rdb** [comment] 2022-12-09 13:45
I spent a while whittling down the test case to something I can wrap my head around.  Here are some observations I gleaned in the process,  which may help you figure out what's wrong with your code:
* You parented the light to the actor, which has a very small scale, so all position changes are multiplied by this scale.
* You always apply the newly created light to *either* the environment *or* to the actor, but never to both, but this may be masked by the fact that…
* You never clear the old lights between test cases, neither from the testlights list nor from the node it was applied to (the clearLights calls were commented out).  Note that removeNode only removes a light from its parent node, but it does not undo the effect of a setLight call.  So you end up with an orphaned node still applied as light to the scene.  I think this is probably the root of your issue; such an orphaned light would no longer inherit the position of any parent nodes, since it has none.

For my own future reference, here is a simplified version of your test case, with proper clearLight calls between the tests.  I do not see any obvious issues exhibited by this test case, so I'm going to finally close this issue, but if you disagree and still think there is a bug, we can reopen it, but please try to describe clearly what exactly the issue is and keep the test code as absolutely simple as possible.
```python
#!/usr/bin/env python3
from direct.showbase.ShowBase import ShowBase
from direct.task import Task
from direct.actor.Actor import Actor
from direct.interval.IntervalGlobal import Sequence, Parallel, Func
from panda3d.core import Point3, PointLight, VBase4

import sys
import os
from math import pi, sin, cos

cam_speed = 0.5


class TestLights(ShowBase):
    # Bookkeeping for the rotation around the model
    angle        = 0.0
    pitch        = 0.0
    adjust_angle = 0
    adjust_pitch = 0
    last_time    = 0.0
    # used to keep track of lights and parents for testing
    testlights   = []

    def __init__(self):
        ShowBase.__init__(self)

        # Load and transform the panda actor.
        self.pandaActor = Actor("models/panda-model",
                                {"walk": "models/panda-walk4"})
        self.pandaActor.setScale(0.005, 0.005, 0.005)
        self.pandaActor.reparentTo(self.render)
        # Loop its animation.
        self.pandaActor.loop("walk")

        # load tutorial scene
        self.scene = self.loader.loadModel("models/environment")
        # Reparent the model to render.
        self.scene.reparentTo(self.render)
        # Apply scale and position transforms on the model.
        self.scene.setScale(0.25, 0.25, 0.25)
        self.scene.setPos(-8, 42, 0)
        # Create the four lerp intervals needed for the panda to
        # walk back and forth.
        pandaPosInterval1 = self.pandaActor.posInterval(
            13,
            Point3(0, -10, 0),
            startPos=Point3(0, 10, 0))
        pandaPosInterval2 = self.pandaActor.posInterval(
            13,
            Point3(0, 10, 0),
            startPos=Point3(0, -10, 0))
        pandaHprInterval1 = self.pandaActor.hprInterval(
            3,
            Point3(180, 0, 0),
            startHpr=Point3(0, 0, 0))
        pandaHprInterval2 = self.pandaActor.hprInterval(
            3,
            Point3(0, 0, 0),
            startHpr=Point3(180, 0, 0))
        # Create and play the sequence that coordinates the intervals.
        self.pandaPace = Sequence(Func(self.dumpLightPos), pandaPosInterval1,
                                  Func(self.dumpLightPos), pandaHprInterval1,
                                  Func(self.dumpLightPos), pandaPosInterval2,
                                  Func(self.dumpLightPos), pandaHprInterval2,
                                  name="pandaPace")
        self.pandaPace.loop()
        # Accept keypresses for looking around
        self.camera.set_pos(sin(self.angle) * 20, -cos(self.angle) * 20, 0)
        self.camera.look_at(0, 0, 0)
        # Key events and camera movement task
        self.accept("arrow_left", self.adjust_turning, [-1.0, 0.0])
        self.accept("arrow_left-up", self.adjust_turning, [1.0, 0.0])
        self.accept("arrow_right", self.adjust_turning, [1.0, 0.0])
        self.accept("arrow_right-up", self.adjust_turning, [-1.0, 0.0])
        self.accept("arrow_up", self.adjust_turning, [0.0, 1.0])
        self.accept("arrow_up-up", self.adjust_turning, [0.0, -1.0])
        self.accept("arrow_down", self.adjust_turning, [0.0, -1.0])
        self.accept("arrow_down-up", self.adjust_turning, [0.0, 1.0])
        self.accept("escape", sys.exit)
        self.taskMgr.add(self.update_camera, 'adjust camera', sort=10)

    def dumpLightPos(self):
        testlights = self.testlights
        print('Light transforms for {} lights'.format(len(testlights)))
        for ndex, (light, parent) in enumerate(testlights):
            try:
                print('Parent getPos/getPos(render):')
                print('relative: {} absolute: {}'.format(
                    parent.getPos(),
                    parent.getPos(self.render),
                ))
                print('Light getPos/getPos(render):')
                print('relative: {} absolute: {}'.format(
                    light.getPos(),
                    light.getPos(self.render),
                ))
                print('Parent getHpr/getHpr(render):')
                print('relative: {} absolute: {}'.format(
                    parent.getHpr(),
                    parent.getHpr(self.render),
                ))
                print('Light getHpr/getHpr(render):')
                print('relative: {} absolute: {}'.format(
                    light.getHpr(),
                    parent.getHpr(self.render),
                ))
            except AssertionError:
                print(
                    'Nodepath for light {} is no longer valid.'.format(
                        (light)
                    ))
                print('reloading light path \'plight\' and recalling.')
                plight = parent.find('plight')
                print('recalling with found NodePath {}.'.format(
                    (plight)))
                self.dumpLightPos([(plight, parent)])

    def addPointToActor(self, illumscene=False):
        # Add pointlight code from manual
        plight = PointLight('plight')
        #plight.setShadowCaster(True)
        plight.setColor(VBase4(0.4, 0.4, 0.8, 1))

        parent = self.pandaActor
        # bind the light to the Actor, it will move
        plnp = parent.attachNewNode(plight)

        # bind the light to the Scene, then translate the scene, the
        # light will not move
        plnp.setPos(.5, .5, 3)
        if illumscene:
            self.scene.setLight(plnp)
        else:
            self.pandaActor.setLight(plnp)
        self.testlights.append((plnp, parent))

    def remove_lights(self):
        for light, parent in self.testlights:
            light.removeNode()
        self.scene.clearLight()
        self.pandaActor.clearLight()
        self.testlights.clear()

    def adjust_turning(self, heading, pitch):
        self.adjust_angle += heading
        self.adjust_pitch += pitch

    def update_camera(self, task):
        if task.time != 0.0:
            dt = task.time - self.last_time
            self.last_time = task.time
            self.angle += pi * dt * self.adjust_angle * cam_speed
            self.pitch += pi * dt * self.adjust_pitch * cam_speed
            # Why /2.001 and not an even 2.0? Because then we'd have to set_Hpr
            # explicitly, as look_at can't deduce the heading when the camera
            # is exactly above/below the spheres center.
            if self.pitch > pi / 2.001:
                self.pitch = pi / 2.001
            if self.pitch < -pi / 2.001:
                self.pitch = -pi / 2.001
            self.camera.set_pos(
                sin(self.angle) * cos(abs(self.pitch)) * 20,
                -cos(self.angle) * cos(abs(self.pitch)) * 20,
                sin(self.pitch) * 20)
            self.camera.look_at(0, 0, 0)
        return Task.cont


if __name__ == '__main__':
    app = TestLights()

    try:
        app.run()
    except SystemExit:
        pass

    app.remove_lights()
    app.addPointToActor(False)
    try:
        app.run()
    except SystemExit:
        pass

    app.remove_lights()
    app.addPointToActor(True)
    try:
        app.run()
    except SystemExit:
        pass
```

**Closed by rdb** 2022-12-09 13:45 UTC
Labels: bug
