### ISSUE TITLE
macOS wheel binaries are not signed

### ISSUE THREAD

**Issue by fran2a** [panda3d/panda3d#1123] opened 2021-03-03 20:32 UTC
Hi. Newbie here...
I encounter an error when using panda3d on mac M1...
Here the message:
"from direct.showbase.ShowBase import ShowBase # pip install panda3d
  File "/opt/homebrew/lib/python3.9/site-packages/direct/showbase/ShowBase.py", line 40, in <module>
    from panda3d.core import *
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/panda3d/core.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/opt/homebrew/lib/python3.9/site-packages/panda3d/core.cpython-39-darwin.so: code signature in (/opt/homebrew/lib/python3.9/site-packages/panda3d/core.cpython-39-darwin.so) not valid for use in process using Library Validation: Trying to load an unsigned library"

Python version 3.9.2 
installed Panda3d with pip3 install panda3d

Thanks

**Comment by rdb** [comment] 2021-03-05 10:37
Do you have an option to "Allow Anyway" in your System Preferences after you encounter the failure?

**Comment by rdb** [comment] 2021-03-07 22:52
Apparently we need to sign the libraries using an "ad hoc" signature:
https://discourse.panda3d.org/t/pip-install-om-m1-mac-works-after-some-pain/27360

**Comment by rdb** [comment] 2021-03-08 14:27
This issue was caused by 783c721cefa32d56b440605f776678634a013a28, it's now fixed in 
576c25b3eab8d3a3501379801fac8c934efe624a and an updated build is available here:
https://buildbot.panda3d.org/downloads/576c25b3eab8d3a3501379801fac8c934efe624a/panda3d-1.10.9.dev130-cp39-cp39-macosx_11_0_universal2.whl

**Comment by fran2a** [comment] 2021-03-08 17:49
Great, It works! Thanks

**Closed** 2021-03-09 09:43 UTC
Labels: build, macos
