### ISSUE TITLE
Multithreaded pipeline screenshot crash

### ISSUE THREAD

**Issue by lachbr** [panda3d/panda3d#360] opened 2018-06-24 05:41 UTC
With `threading-model App/Cull/Draw` (or any combination for that matter), calling `base.win.getScreenshot()` crashes the application. The application will just freeze for a second and then close, there doesn't appear to be any error dialog boxes or console output.
```
from panda3d.core import *
loadPrcFileData("", "notify-level info")
loadPrcFileData("", "default-directnotify-level info")
loadPrcFileData("", "threading-model App/Cull/Draw")

from direct.showbase.ShowBase import ShowBase
base = ShowBase()

base.accept('s', base.win.getScreenshot)

base.run()
```

**Comment by rdb** [comment] 2018-06-25 08:20
Which exact version of Panda are you using, on which operating system?  The code you showed works fine for me, and I can recall fixing a bug with `getScreenshot` and the multithreaded pipeline in the past.

**Comment by kamgha** [comment] 2018-06-26 10:40
I can confirm that the code above crashes with the current git master (`371e60c`) after pressing the "S"-Key, built for Windows 64bit without Eigen. The crash occurs only on OpenGL (`load-display pandagl`), DirectX 9 and TinyDisplay do not show any issue.

**Comment by rdb** [comment] 2018-07-05 17:08
Problem is that `get_screenshot()` is binding the GL context to the current thread, which is not OK when the draw thread might still have the GL context bound.  This can be fixed by waiting for the draw thread to be done rendering and then asking the draw thread to do the screenshot.

Doing so does stall the multithreaded pipeline because of the synchronous nature of `get_screenshot()`.  If you need to make screenshots on a regular basis, it would be better bind a texture with `RTM_triggered_copy_ram` and then call `trigger_copy()` whenever you want the screenshot, which returns an `AsyncFuture`.

Fix will be pushed imminently.

**Closed** 2018-07-05 17:57 UTC
