### ISSUE TITLE
Multithreaded pipeline and parenting nodes to joints

### ISSUE THREAD

**Issue by lachbr** [panda3d/panda3d#271] opened 2018-03-05 01:17 UTC
Nodes which are parented to joints are out of sync:
https://gyazo.com/2e541895de939e2b89464fd29bd4eb1a.gif
The pie is parented to a joint of the hand, and the three body parts (head, torso, legs) are parented to a joint of the underneath body part. The pie and all three body parts seem to lag behind their parents in the App/Cull/Draw threading model.
The animations are compressed using FFTW, if that would have any kind of effect.

**Comment by CFSworks** [comment] 2018-03-05 01:27
This looks like it might be the same root cause as (possibly even a duplicate of) #256.

I'm not too well-versed in Panda's skeletal animation subsystem, but I would **guess** that vertex deformation is performed in the Cull stage, while the `CharacterJointEffect` is applied in App. This would explain the behavior you're seeing: skeletal animation doesn't happen until a frame after the one currently being processed by the App stage, so the App stage applies stale joint transforms to the node in the scenegraph.

Does this happen in `threading-model /Draw` (i.e. App+Cull together, Draw on its own thread)?

**Comment by lachbr** [comment] 2018-03-05 03:03
@CFSworks There is still a noticeable discrepancy on /Draw, but not as much compared to App/Cull/Draw.

**Comment by CFSworks** [comment] 2018-03-05 04:12
How about `threading-model CullDraw` (no `/`)?

**Comment by CFSworks** [comment] 2018-03-05 08:24
The issue is that, while the `CharacterJointEffect` does read straight through to the `PartBundle` and get an accurate transform for the current stage in the pipeline, the character vertex skinning is not pipelined properly (and is probably coming from some combination of the app and cull threads).

I'm closing this in favor of #272 (which is the issue for tracking adding such support).

**Closed by CFSworks** 2018-03-05 08:24 UTC
