### ISSUE TITLE
please add type stub files for vscode's pylance language server. 

### ISSUE THREAD

**Issue by BlackEagle1983** [panda3d/panda3d#1329] opened 2022-07-05 06:15 UTC
Hello . Me and my friends use VScode for programming python and panda3d  but when we want to import **ai** or **core** modules vscode's pylance language server does not recognize contents of these files . I told this issue to Microsoft and they said the reason is for lacking type stub files . please add these files for being  compatible with vscode editor . 
![175804487-ec873f52-cf60-4b5c-9164-d1c416b1d595](https://user-images.githubusercontent.com/72033451/177261708-86fcc7dc-d727-46b6-b550-bfe7587b87cf.png)

**Comment by rdb** [comment] 2022-07-05 06:36
Duplicate of #1327

**Closed by rdb** 2022-07-05 06:36 UTC
Labels: enhancement
